# Generated by Django 4.0.4 on 2022-05-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The user's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="The user's last name.", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='The item the user.', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created.')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoListApp.user')),
            ],
        ),
    ]
